#!/usr/bin/env ruby
require 'yaml'
require 'aligned_table'

list = YAML.load_file(File.expand_path("~/.flexget/config.yml"))
series = list["templates"]["anime"]["series"]

at = AlignedTable.new
at.title = "Airing Anime List"

rows = series.map do |serie|
  name, metadata = serie.first
  name = name.gsub(/_/, " ")[0,30]
  subgroup = "[#{metadata["from_group"]}]"
  [subgroup, name]
end

rows.push([nil, :-])
rows.push([nil, "Total: #{series.length}"])

at.rows = rows
puts at.render
