#!/usr/bin/env ruby
require 'yaml'
require 'aligned_table'

list = YAML.load_file(File.expand_path("~/.flexget/config.yml"))
series = list["templates"]["anime"]["series"]

at = AlignedTable.new

group_list = series.group_by { |x| x.values[0]["from_group"] }.map { |k,v| [k, v.count] }
group_list = Hash[*group_list.sort { |a,b| b[1] <=> a[1] }.flatten]

puts "Subgroup Stats for Airing Anime:"
rows = group_list.map do |group, count|
  subgroup = "[#{group}]"
  percent = ((count.to_f / series.length)*100).round(2)
  [subgroup, count, "(#{percent}%)"]
end
rows.push(["Total:", series.length])
at.rows = rows
puts at.render

